name: aoc
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9
